[package]
name = "textdistance"
version = "1.0.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }

[lib]
crate-type = ["cdylib"]

# Optimization profiles
[profile.release]
opt-level = 3             # Maximum optimization